CREATE DATABASE [studio] ON  PRIMARY 
( NAME = N'studio', FILENAME = N'c:\Programmi\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\studio.mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'studio_log', FILENAME = N'c:\Programmi\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\studio_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [studio] SET COMPATIBILITY_LEVEL = 100
GO
ALTER DATABASE [studio] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [studio] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [studio] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [studio] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [studio] SET ARITHABORT OFF 
GO
ALTER DATABASE [studio] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [studio] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [studio] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [studio] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [studio] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [studio] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [studio] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [studio] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [studio] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [studio] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [studio] SET  DISABLE_BROKER 
GO
ALTER DATABASE [studio] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [studio] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [studio] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [studio] SET  READ_WRITE 
GO
ALTER DATABASE [studio] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [studio] SET  MULTI_USER 
GO
ALTER DATABASE [studio] SET PAGE_VERIFY CHECKSUM  
GO
USE [studio]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [studio] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
